DROP TRIGGER IF EXISTS `deleteBlockProps`;
DROP TABLE IF EXISTS `blockProps`;
DROP TRIGGER IF EXISTS `patchBlockPath`;
DROP TABLE IF EXISTS `blocks`;
DROP TABLE IF EXISTS `pages`;
DROP TABLE IF EXISTS `pageTypes`;
DROP TABLE IF EXISTS `plugins`;
DROP TABLE IF EXISTS `theWebsite`;

CREATE TABLE `theWebsite` (
    `name` VARCHAR(92) NOT NULL,
    `lang` VARCHAR(12) NOT NULL,
    `aclRules` JSON,
    `lastUpdatedAt` INT(10) UNSIGNED DEFAULT 0
) DEFAULT CHARSET = utf8mb4;

CREATE TABLE `plugins` (
    `id` SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT,
    `name` VARCHAR(92) NOT NULL,
    `status` TINYINT(1) NOT NULL,
    PRIMARY KEY (`id`)
) DEFAULT CHARSET = utf8mb4;

CREATE TABLE `pageTypes` (
    `id` SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT,
    `name` VARCHAR(92)  NOT NULL,
    `fields` JSON,
    `isListable` TINYINT(1) DEFAULT 1,
    PRIMARY KEY (`id`)
) DEFAULT CHARSET = utf8mb4;

CREATE TABLE `pages` (
    `id` MEDIUMINT UNSIGNED NOT NULL PRIMARY KEY AUTOINCREMENT,
    `slug` VARCHAR(92) NOT NULL,
    `path` VARCHAR(191) NOT NULL, -- 191 * 4 = 767 bytes = max key length
    `level` TINYINT(1) UNSIGNED NOT NULL DEFAULT 1,
    `title` VARCHAR(92) NOT NULL,
    `layout` VARCHAR(128) NOT NULL,
    `status` TINYINT(1) NOT NULL DEFAULT 0,
    `pageTypeId` SMALLINT UNSIGNED NOT NULL,
    FOREIGN KEY(`pageTypeId`) REFERENCES `pageTypes`(`id`)
) DEFAULT CHARSET = utf8mb4;

CREATE TABLE `blocks` (
    `id` INT UNSIGNED NOT NULL PRIMARY KEY AUTOINCREMENT,
    `path` VARCHAR(191) NOT NULL,
    `type` VARCHAR(48) NOT NULL,
    `section` VARCHAR(48) NOT NULL,
    `renderer` VARCHAR(128) NOT NULL,
    `pageId` MEDIUMINT UNSIGNED NOT NULL,
    `title` VARCHAR(48) DEFAULT NULL,
    FOREIGN KEY(`pageId`) REFERENCES `pages`(`id`),
) DEFAULT CHARSET = utf8mb4;

DELIMITER //
CREATE TRIGGER `patchBlockPath` BEFORE INSERT ON `blocks`
FOR EACH ROW BEGIN
    IF NEW.`path` = '' THEN
        SET NEW.`path` = CONCAT(NEW.`id`, '/');
    END IF;
END//
DELIMITER ;

CREATE TABLE `blockProps` (
    `id` INT UNSIGNED NOT NULL PRIMARY KEY AUTOINCREMENT,
    `key` VARCHAR(48) NOT NULL,
    `value` TEXT,
    `blockId` INT UNSIGNED NOT NULL,
    FOREIGN KEY(`blockId`) REFERENCES `blocks`(`id`)
) DEFAULT CHARSET = utf8mb4;

DELIMITER //
CREATE TRIGGER `deleteBlockProps` BEFORE DELETE ON `blocks`
FOR EACH ROW BEGIN
    DELETE FROM `blockProps` WHERE `blockId` = old.`id`;
END//
DELIMITER ;
