<?php

define("SIVUJETTI_INDEX_PATH", "");
define("SIVUJETTI_BACKEND_PATH", "");
define("SIVUJETTI_SITE_PATH", "");
define("SIVUJETTI_PLUGINS_PATH", "");
define("SIVUJETTI_DEVMODE", 1 << 1);
define("SIVUJETTI_FLAGS",   SIVUJETTI_DEVMODE);
